# Generated by Django 2.0.2 on 2018-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('product_seller', models.CharField(max_length=250)),
                ('product_old_price', models.CharField(max_length=250)),
                ('product_current_price', models.CharField(max_length=250)),
                ('product_url', models.CharField(max_length=1500)),
                ('product_categories', models.CharField(max_length=1500)),
                ('product_valid_sizes', models.CharField(max_length=500)),
                ('product_off', models.CharField(max_length=100)),
                ('product_valid_images', models.CharField(max_length=1500)),
                ('product_news', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
