# Generated by Django 2.0.2 on 2018-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='product_price_change_type',
            field=models.CharField(default='down', max_length=100),
        ),
    ]
