# Generated by Django 2.0.3 on 2018-03-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180319_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='product_color',
            field=models.CharField(default='Not Available in Colors', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='Not Available in Colors', max_length=100),
        ),
    ]
