# Generated by Django 2.0.3 on 2018-03-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180323_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='product_color_change',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='product_size_change',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
