# Generated by Django 2.0.3 on 2018-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180404_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='product_color',
            field=models.CharField(default=['Not Available in Colors'], max_length=500),
        ),
    ]
